data:
  type: image
  train_dir: data/Flowers_1000_sub
  lsun_categories_train: null
  lsun_categories_test: null
  simple_transform: true
  img_size: 128
  nlabels: 1
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  dim: 256
training:
  nworkers: 8
  batch_size: 32
  epochs: 2000
  lr: 0.005
  pretrain_ckpt_file: pretrained_ckpt/ImageNetPre_generator.pt
  class_embedding: output/flowers_sub1000/class_embedding/class_embedding.npy
  fix_class_embedding: false
  save_per_epoch: 100
  out_dir: output/vec2img/flowers_sub1000
  lr_scheduler:
    milestones_step: 1500
    gamma: 0.1
