data:
  type: image
  train_dir: data/Flowers
  test_dir: data/Flowers
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  simple_transform: true
  img_size: 128
  nlabels: 1
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: gauss
  dim: 256
training:
  use_regularization: false
  regularization:
    type: l2
    lambda : 0.01
  nworkers: 8
  batch_size: 64
  iter_per_batch: 10000
  lr: 0.1
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  omit_embedding_layer: true
  out_dir: output/vec2img/flowers_batch_mode
  lr_scheduler: 
    step_size: 8000
    gamma: 0.1
