data:
  type: image
  train_dir: data/LSUN/kitchen_minitrain_png
  test_dir: data/LSUN/kitchen_val_png
  simple_transform: true
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  img_size: 256
  nlabels: 1
generator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  load_from: 'output/vec2img/lsun_kitchen/chkpts_old/epoch_100_latent_vecs_embedding_layer.pth'
  nworkers: 8
  batch_size: 64
  epochs: 1000
  lr: 0.0005
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/lsunbedroom/lsun_bedroom-df4e7dd2.pt
  save_per_epoch: 20
  out_dir: output/vec2img/lsun_kitchen
  lr_scheduler:
    milestones_step: 900
    gamma: 0.1
