data:
  type: image
  train_dir: data/Flowers
  test_dir: data/Flowers
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  simple_transform: true
  img_size: 128
  nlabels: 1
generator:
  name: resnet2_omit_class_embedding
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    split: false
z_dist:
  type: gauss
  dim: 64
training:
  use_regularization: false
  regularization:
    type: l2
    lambda : 0.01
  nworkers: 8
  batch_size: 128
  iter_per_batch: 10000
  lr: 0.1
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  omit_embedding_layer: true
  out_dir: output/vec2img/flowers_64dim_batchmode
  lr_scheduler: 
    step_size: 8000
    gamma: 0.1
