data:
  type: image
  train_dir: data/Flowers_split
  test_dir: data/Flowers_split
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  simple_transform: true
  img_size: 128
  nlabels: 102
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: gauss
  dim: 256
training:
  load_from: null
  use_regularization: false
  regularization:
    type: l2
    lambda : 0.01
  nworkers: 8
  batch_size: 32
  epochs: 10000
  lr: 0.1
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  omit_embedding_layer: true
  save_per_epoch: 100
  out_dir: output/vec2img/flowers
  lr_scheduler:
    milestones_step: 7000
    gamma: 0.1
