data:
  type: image
  train_dir: data/LSUN/kitchen_minitrain_png
  test_dir: data/LSUN/kitchen_val_png
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  img_size: 256
generator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
discriminator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gmm
  dim: 256
  gmm_components_weight: output/vec2img/lsun_kitchen_mini_train_batch_mode/gmm_components_weights.npy
  gmm_mean: output/vec2img/lsun_kitchen_mini_train_batch_mode/gmm_mean.npy
  gmm_cov: output/vec2img/lsun_kitchen_mini_train_batch_mode/gmm_cov.npy
training:
  batch_size: 64
  pretrain_ckpt_file: ./pretrained_ckpt/lsunbedroom/lsun_bedroom-df4e7dd2.pt
  finetune: true
  out_dir: output/finetune/lsun_kitchen_gmm_batchmode_vec2img_bs64
  inception_every: -1
  fid_every: 1000
  fid_fake_imgs_num: 50000
test:
  model_file: 'model.pt'
  batch_size: 32 
  sample_size: 64 
  sample_nrow: 8
  compute_inception: false
  compute_fid: true
  fid_fake_imgs_num: 50000
interpolations:
  nzs: 10
  nsubsteps: 75
