data:
  type: image
  train_dir: data/Flowers
  test_dir: data/Flowers
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  img_size: 128
  nlabels: 1
generator:
  name: resnet2_omit_class_embedding
  kwargs:
    nfilter: 64
    nfilter_max: 1024
discriminator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: none  # gauss
  dim: 512
training:
  batch_size: 32
  change_generator_embedding_layer: true
  change_discriminator_fc_layer: true
  pretrain_ckpt_file: ./pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  finetune: true
  out_dir: output/finetune/flowers_512dim_autoshift_shuffle_small_lr
  inception_every: -1
  fid_every: 1000
  fid_fake_imgs_num: 8000
  lr_g: 0.000025
  lr_d: 0.000025
  max_epoch: 140
  lr_s: 0.000025
  take_model_average: true # false?
test:
  model_file: 'model.pt'
  batch_size: 32 
  sample_size: 64 
  sample_nrow: 8
  compute_inception: false
  compute_fid: true
  fid_fake_imgs_num: 8000
