data:
  type: image
  train_dir: data/LSUN/kitchen_minitrain_png
  test_dir: data/LSUN/kitchen_val_png
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  img_size: 256
generator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
discriminator:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  batch_size: 64
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/lsunbedroom/lsun_bedroom-df4e7dd2.pt
  finetune: true
  out_dir: output/finetune/lsun_kitchen
  inception_every: 100
test:
  model_file: ''
  batch_size: 32 
  sample_size: 64 
  sample_nrow: 8
  compute_inception: true
interpolations:
  nzs: 10
  nsubsteps: 75
