data:
  type: image
  train_dir: data/Flowers
  test_dir: data/Flowers
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  simple_transform: true
  img_size: 128
  nlabels: 1000
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
im2latent:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gauss
  dim: 256
training:
  load_from: null
  nworkers: 8
  batch_size: 64
  total_iters: 10000
  lr: 0.0001
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  label_embedding: output/vec2img2vec/imagenet/class_embedding/class_embedding.npy
  save_per_iter: 100
  out_dir: output/vec2img2vec/imagenet
  lr_scheduler:
    step_size: 5000
    gamma: 0.1
