data:
  type: image
  train_dir: data/Flowers_1000_sub_cls
  test_dir: data/Flowers_1000_sub
  lsun_categories_train: null
  lsun_categories_test: null
  img_size: 128
  nlabels: 10
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
discriminator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: gmm
  dim: 256
  gmm_components_weight: output/vec2img/flowers_sub1000_cls_256dim_special_init/gmm_components_weights_components.npy
  gmm_mean: output/vec2img/flowers_sub1000_cls_256dim_special_init/gmm_mean.npy
  gmm_cov: output/vec2img/flowers_sub1000_cls_256dim_special_init/gmm_cov.npy
training:
  batch_size: 32
  change_generator_embedding_layer: true
  change_discriminator_fc_layer: true
  pretrain_ckpt_file: null
  generator_pretrained_ckpt_file: output/vec2img/flowers_sub1000_cls_256dim_special_init/chkpts/generator.pth
  discriminator_pretrained_ckpt_file: ./pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  finetune: true
  out_dir: output/finetune/flowers_sub1000_cls_256dim_gmm_small_lr_special_init
  inception_every: -1
  fid_every: 1000
  fid_fake_imgs_num: 8000
  lr_g: 0.000025
  lr_d: 0.000025
test:
  model_file: 'model.pt'
  batch_size: 32 
  sample_size: 64 
  sample_nrow: 8
  compute_inception: false
  compute_fid: true
  fid_fake_imgs_num: 8000
