data:
  type: image
  train_dir: data/Flowers_25
  test_dir: data/Flowers251
  lsun_categories_train: null
  lsun_categories_test: null
  img_size: 128
  nlabels: 1
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
discriminator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: kde
  dim: 256
  latentvec_dir: output/vec2img/flowers25_256dim_special_init_fix/latentvecs
training:
  batch_size: 25
  change_generator_embedding_layer: true
  change_discriminator_fc_layer: true
  pretrain_ckpt_file: null
  generator_pretrained_ckpt_file: output/vec2img/flowers25_256dim_special_init_fix/chkpts/generator.pth
  discriminator_pretrained_ckpt_file: ./pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  finetune: true
  out_dir: output/finetune/flowers25_256dim_kde_small_lr_special_init_fix
  inception_every: -1
  fid_every: 1000
  sample_every: 1000
  fid_fake_imgs_num: 25
  lr_g: 0.000025
  lr_d: 0.000025
  max_epoch: 60000
  save_every: 1000
test:
  model_file: 'model_best.pt'
  batch_size: 25 
  sample_size: 64 
  sample_nrow: 8
  compute_inception: false
  compute_fid: true
  fid_fake_imgs_num: 251
