data:
  type: image
  train_dir: data/cityscapes_sub10000_cls5
  test_dir: data/cityscapes_sub1000_cls5
  lsun_categories_train: null
  lsun_categories_test: null
  simple_transform: true
  img_size: 128
  nlabels: 5
generator:
  name: resnet2
  kwargs:
    nfilter: 64
    nfilter_max: 1024
    embed_size: 256
z_dist:
  type: gauss
  dim: 256
training:
  load_from: null
  use_regularization: false
  regularization:
    type: l2
    lambda : 0.01
  nworkers: 8
  batch_size: 32
  epochs: 2000
  lr: 0.005
  pretrain_ckpt_file: pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  omit_embedding_layer: true
  class_embedding: output/cityscapes_sub1000/class_embedding/class_embedding.npy
  fix_class_embedding: false
  save_per_epoch: 100
  out_dir: output/vec2img/cityscapes_sub1000_cls5_256dim_special_init
  lr_scheduler:
    milestones_step: 1500
    gamma: 0.1
