data:
  type: image
  train_dir: data/Flowers
  test_dir: data/Flowers
  simple_transform: true
  lsun_categories_train: [kitchen_train]
  lsun_categories_test: [kitchen_val]
  img_size: 128
  nlabels: 1
generator:
  name: resnet2_omit_class_embedding
  kwargs:
    nfilter: 64
    nfilter_max: 1024
im2latent:
  name: resnet3
  kwargs:
    nfilter: 64
    embed_size: 1
z_dist:
  type: gauss
  dim: 512
training:
  load_from: null
  use_pretrained_img_feature_extractor: false  
  use_regularization: true
  regularization:
    type: kl
    lambda : 0.1
  nworkers: 8
  batch_size: 64
  epochs: 1000
  lr: 0.0001
  omit_embedding_layer: true
  pretrain_ckpt_file: /home/zhangzr/GAN_stability/pretrained_ckpt/imagenet/imagenet-8c505f47.pt
  save_per_epoch: 20
  out_dir: output/img2vec2img/flowers_512dim_reg
  lr_scheduler:
    milestones_step: 800
    gamma: 0.1
